### ISSUE TITLE
ActiveMq+android-mqtt

### ISSUE THREAD

**Issue by Eminem8080** [JesseFarebro/android-mqtt#9]
when I close wife and reconnected 
  `at de.eclipsemagazin.mqtt.push.MqttService.sendKeepAlive(MqttService.java:426)`
` at de.eclipsemagazin.mqtt.push.MqttService.keepAlive(MqttService.java:328)`
`at de.eclipsemagazin.mqtt.push.MqttService.onStartCommand(MqttService.java:171)`
Would you mind answering this quesstions?

**Comment by dxslin** [comment]
The service stoped after a period time and I can't  receive the mqtt message.
Could you help me to solve it.

**Comment by JesseFarebro** [comment]
@dxslin you *can't* receive messages?

@Eminem8080 I don't understand you're question. You disconnect from the network and it crashes?

**Comment by dxslin** [comment]
I can receive  messages, but I can't receive the messages after a period time. And I also met you such problem.
